# Numpy的简单使用

## 安装

```shell
pip install numpy
# 注意使用的是pip还是pip3, 以及必要的管理员权限
# 推荐使用virtualenv来构建一个虚拟环境
```

## Numpy中矩阵的一些属性

In [1]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print("所创建的A:\n", A)
print("A的维度: ", A.ndim)  # 2
print("A的行列: ", A.shape)  # (2,3)
print("A的大小: ", A.size)  # 6


## Numpy中矩阵的创建

### 普通创建与指定数据类型

In [2]:
# 矩阵的普通创建
a = np.array([[2, 23, 4], [2, 32, 4]])
# print(a)
# [[ 2 23  4]
#  [ 2 32  4]]

# 指定矩阵中元素的数据类型
a = np.array([2, 23, 4], dtype=np.int64)
print(a.dtype)  # int64
a = np.array([2, 23, 4], dtype=np.float64)
print(a.dtype)  # float64
a = np.array([2, 23, 4], dtype=np.double)
print(a.dtype)  # float64


### 零矩阵、全一矩阵和空矩阵的创建

In [3]:
# 零矩阵 参数 (x,y) 为 x行y列
a1 = np.zeros((3, 4))
print(a1)

# 全一矩阵 参数 (x,y) 为 x行y列
a2 = np.ones((3, 4))
print(a2)

# 空矩阵 参数 (x,y) 为 x行y列
a3 = np.empty((3, 3))
print(a3)


### 生成数列和随机数矩阵

In [4]:
# 随机生成0到1之间的数，2行4列
a = np.random.random((2, 4))
print(a)

# 生成范围为[10,20)的数列，步长为2
a = np.arange(10, 20, 2)
print(a)  # [10 12 14 16 18]


### 等差数列与等比数列

In [5]:
# 等差数列
# 生成范围为[1,100]，生成10个数,且等差
a = np.linspace(1, 100, 10)
print(a)

# 等比数列
# 生成范围为[0,9]，生成10个数,且等比
a = np.logspace(0, 9, 10, base=2)
print(a)


上述等比数列其实就是求 $ \log_{base} X $ , 其中 $X$ 为 $\frac{生成范围}{生成的个数}$ 后的每一个对应的数. 因此这个参数base就是公比.



### 将数列reshape成矩阵

In [6]:
# 生成范围为[0,12)的数列，步长为1，并塑造为3行4列的矩阵
a = np.arange(12).reshape((3, 4))
print(a)


## 矩阵的基础运算

### 数列的加,减,数乘,乘方,函数运算

In [7]:
a = np.arange(10, 50, 10)
b = np.arange(4)
print("a:\n", a, "\nb:\n", b)  # [10 20 30 40] [0 1 2 3]

c = a + b
print("a + b :\n", c)  # [10 21 32 43]

c = a - b
print("a - b :\n", c)  # [10 19 28 37]

print("a**2 :\n", a**2)  # [ 100  400  900 1600]

c = 10 * a
print("10*a :\n", c)  # [100 200 300 400]
print("10*a < 111 :\n", c < 111)  # [ True False False False]
print("10*a == 200 :\n", c == 200)  # [ False True False False]

c = np.sin(a)
print("np.sin(a) :\n", c)  # [-0.54402111  0.91294525 -0.98803162  0.74511316]


### 矩阵的数乘,乘法和转置

In [8]:
a = np.array([[4, 2], [1, 3]])
b = np.arange(4).reshape((2, 2))
print("a:\n", a, "\nb:\n", b)
# [[1 2]
#  [2 3]]
#  [[0 1]
#  [2 3]]

print("a*b :\n", a * b)
# [[0 2]
#  [4 9]]

print("a@b :\n", a @ b)
# print(np.dot(a, b))
# print(a.dot(b))
# [[ 4  7]
#  [ 6 11]]

# 转置矩阵
print("np.transpose(a) :\n", np.transpose(a))
print("a.T :\n", a.T)


### 其他运算

In [9]:
a = np.arange(4).reshape((2, 2))
print(a)
print("np.sum(a):", np.sum(a))
print("np.max(a):", np.max(a))
print("np.min(a):", np.min(a))
# axis=0,1 为 行，列
print('np.max(a, axis=0):',np.max(a, axis=0))
print('np.sum(a, axis=1):',np.sum(a, axis=1))
print('np.min(a, axis=1):',np.min(a, axis=1))


In [10]:
a = np.array([1, 8, 15, 6, 55, 99, 125, 10, 23, 15, 89, 52]).reshape((3, 4))
print("a:\n",a)

# 输出最大最小值的索引
print("输出最大最小值的索引:")
print(np.argmin(a))  # 0
print(np.argmax(a))  # 6

# 平均值
print("平均值:")
print(np.average(a))  # 41.5
print(a.mean())  # 41.5
# 中位数
print("中位数:")
print(np.median(a))  # 19

# 前N项和数列; 累加数列
print("前N项和数列; 累加数列:")
print(np.cumsum(a))  # [  1   9  24  30  85 184 309 319 342 357 446 498]

# 累差数列
print("累差数列:")
print(np.diff(a))
# [[   7    7   -9]
#  [  44   26 -115]
#  [  -8   74  -37]]

# 找出非零元素
print("找出非零元素:")
print(np.nonzero(a))
# (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
# 获得非零元素的行索引矩阵和列索引矩阵

# 排序
print("排序:")
print(np.sort(a))  # 逐行排序


# clip 限制矩阵的范围 使不超出min max
print("clip 限制矩阵的范围 使不超出min max :")
min = 5
max = 50
print(np.clip(a, min, max))
# [[ 5  8 15  6]
#  [50 50 50 10]
#  [23 15 50 50]]

## 索引与切片与迭代与扁平化

In [11]:
a = np.array([1, 8, 15, 6, 55, 99, 125, 10, 23, 15, 89, 52]).reshape((3, 4))
print(a)
# [[  1   8  15   6]
#  [ 55  99 125  10]
#  [ 23  15  89  52]]

print("切片:")
print(a[2])  # [23 15 89 52]
print(a[:, 1])  # [ 8 99 15]
print(a[2][1])  # 15
print(a[2, 1])  # 15
print(a[2, 1:3])  # [15 89]


# 迭代 iteration
print("迭代行:")
for row in a:  # 迭代行
    print(row)
# [15 89]
# [ 1  8 15  6]
# [ 55  99 125  10]
# [23 15 89 52]

print("通过迭代转置矩阵迭代列:")
for column in a.T:  # 通过迭代转置矩阵迭代列
    print(column)
# [ 1 55 23]
# [ 8 99 15]
# [ 15 125  89]
# [ 6 10 52]

print("扁平化为一行,并遍历:")
# 扁平化为一行,并遍历
for item in a.flat:
    print(item)


##  合并矩阵

In [12]:
a = np.array([1, 1, 1])
b = np.array([2, 2, 2])
print("a:\n", a, "\nb:\n", b)

# 上下合并
print("上下合并:")
c = np.vstack((a, b))
print(c)
# print(a.shape, c.shape)  # (3,) (2, 3)
# 左右合并
print("左右合并:")
c = np.hstack((a, b))
print(c)
# print(a.shape, c.shape)  # (3,) (6,)

# # 将序列变为列矩阵 增维
# a = a[:, np.newaxis]
# b = b[:, np.newaxis]
# c = np.hstack((a, b))
# print(a)
# # [[1]
# #  [1]
# #  [1]]
# print(a.shape, c.shape)  # (3,1) (3,2)

# # 合并 axis 0 1 为 纵向 横向
# c = np.concatenate((a, b, b, a), axis=0)
# print(c)
# c = np.concatenate((a, b, b, a), axis=1)
# print(c)

## 分割矩阵

In [13]:
a = np.arange(12).reshape((3,4))
print("a:\n", a)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# np.split(array, section, axis)
print("在0轴上分割矩阵(0轴向下,1轴向右),也称为垂直分割:")
# print(np.split(a,3,axis=0))
print(np.vsplit(a,3))
# [array([[0, 1, 2,  3]]), 
#  array([[4, 5, 6,  7]]), 
#  array([[8, 9, 10, 11]])]

print("在1轴上分割矩阵(0轴向下,1轴向右),也称为水平分割:")
# print(np.split(a,2,axis=1))
print(np.hsplit(a,2))
# [array([[0, 1],
#        [4, 5],
#        [8, 9]]), 
#  array([[ 2,  3],
#        [ 6,  7],
#        [10, 11]])]

# 不等份分割
print("分割时无法等分的情况:")
print(np.array_split(a,3,axis=1))
# [array([[0, 1],
#        [4, 5],
#        [8, 9]]), 
#  array([[ 2],
#        [ 6],
#        [10]]),
#  array([[ 3],
#        [ 7],
#        [11]])]


## 深拷贝与浅拷贝

### 浅拷贝

In [14]:
a = np.arange(4)
b = a
c = b
print("浅拷贝中的a,b,c是同一个矩阵,对其中一个更改,会影响其他")
print("b is a ? :", b is a)
print("c is a ? :", c is a)


### 深拷贝

In [15]:
a = np.arange(4)
b = a.copy()
print("a: {}".format(a))
print("b: {}".format(b))

b[1] = 0
print("修改b[1] = 0")
print("a: {}".format(a))
print("b: {}".format(b))